apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/auth-secret: basic-auth-secret
    nginx.ingress.kubernetes.io/auth-type: basic
  name: prometheus
  namespace: monitoring
spec:
  ingressClassName: nginx
  rules:
  - host: prometheus-i7oqvu.yun-paas.com
    http:
      paths:
      - backend:
          service:
            name: prometheus-k8s
            port: 
              number: 9090
        path: null
        pathType: ImplementationSpecific
